### ISSUE TITLE
Plugin seems to have stopped working after latest CS2 update

### ISSUE THREAD

**Issue by alnoisegit** [LordFetznschaedl/CS2Rcon#6]
Everything was working fine before the update, but after updating using any rcon command gives the following error in console.

```[All Chat][alnoise (410505906)]: !rcon status
21:33:38 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'logger')
   at System.ThrowHelper.Throw(String paramName)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, EventId eventId, Exception exception, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.Log(ILogger logger, LogLevel logLevel, String message, Object[] args)
   at Microsoft.Extensions.Logging.LoggerExtensions.LogInformation(ILogger logger, String message, Object[] args)
   at CS2_SimpleAdmin.Helper.LogCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/Helper.cs:line 152
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnRconCommand(CCSPlayerController caller, CommandInfo command) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/Commands/basecommands.cs:line 612
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager9
   at InvokeStub_Action`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

This is on Linux running CSS v213

**Comment by LordFetznschaedl** [comment]
Hi @alnoisegit 

This has nothing todo with my plugin. The error happens in CS2_SimpleAdmin
